name: Dependabot Auto-merge

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
    - name: Check PR details
      id: pr-details
      run: |
        echo "PR title: ${{ github.event.pull_request.title }}"
        echo "PR author: ${{ github.actor }}"
        
        # Check if it's a patch or minor update (safe to auto-merge)
        if [[ "${{ github.event.pull_request.title }}" =~ ^Bump.*from.*to.* ]]; then
          echo "auto_merge=true" >> $GITHUB_OUTPUT
        else
          echo "auto_merge=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Enable auto-merge
      if: steps.pr-details.outputs.auto_merge == 'true'
      run: |
        gh pr merge ${{ github.event.pull_request.number }} \
          --auto \
          --squash \
          --delete-branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Add auto-merge comment
      if: steps.pr-details.outputs.auto_merge == 'true'
      run: |
        gh pr comment ${{ github.event.pull_request.number }} \
          --body "🤖 Auto-merge enabled for this dependency update. Will merge automatically once CI passes."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}